# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6146d3b5046ccb200f628d29d25cafbeb0c4d63a19d412c8133fc2e7375624be50c916cd99673c3dc3849d5da84e6ee81977cba1f72dfd731c41e7330efa5f87
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>


test:
  secret_key_base: 3ca7d7c68acaec9dc31c1c7f26c09a9bfcde976065e9b344609a070f14df3a84fd7955d855ac64954dafe5503487027daebbfd433eceb37a8f84853393ba98a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>